### ISSUE TITLE
Classes IdolJaxbMarshaller and IdolJaxbMarshaller don't exist

### ISSUE THREAD

**Issue by mt3o** [hpe-idol/java-idol-utils#2]
They probably should be here:
https://github.com/hpe-idol/java-idol-utils/blob/develop/src/main/java/com/hp/autonomy/idolutils/IdolXmlMarshaller.java

But they are not. Please fix.

**Comment by tung-jin-chew-hp** [comment]
Hi, java-idol-types version > 1.00 has replaced this library, as noted on https://github.com/hpe-idol/java-idol-types/commit/e94ef2d5b3640f0ec1d49645b2bdba95644b46cd . Please use that instead.
